### ISSUE TITLE
Add shortener option

### ISSUE THREAD

**Issue by drym3r** [andstatus/andstatus#319] opened 2015-12-23 12:08 UTC
Hi. It would be nice to add a shortener option, since in the GS nodes which have a 140 char limit, it's not easy to post links with its tittle. 
If you don't know which shortener you could use, you could use qvitter's (qttr.at). I'm actually using it for some program, it's in python, but it could serve to orient you. It's the shortener function.
[gnusrss](https://notabug.org/drymer/gnusrss/commit/b23991fd71dc8cf2b808647e26e84c7a026187d8)
Thanks

**Comment by yvolk** [comment] 2015-12-24 15:55
This is a duplicate of #32 Please see and discuss there.

**Closed by yvolk** 2015-12-24 15:55 UTC
