### ISSUE TITLE
Timeline doesn't restore its state (was: Combined timeline keeps opening)

### ISSUE THREAD

**Issue by gjedeer** [andstatus/andstatus#389] opened 2016-06-18 08:43 UTC
A lot of actions lead to displaying "combined" feed, when not explicitly asked. Two actions I know are easily reproducible:
- Leaving the app for a second (pressing the Back button one time too much, and holding the Home button to go back to it again)
- Changing screen orientation: this is absurd but I tilted my phone and the screen has gone blank and Combined feed was displayed

But there's more, I was completely disoriented by this when I first started using &s, then I learned to pay close attention to the feed selection widget.

**Comment by yvolk** [comment] 2016-06-20 05:56
Thank you for noticing. Currently I'm redoing the whole list of timelines, and will keep an eye on this problem also.

**Comment by bulletbites** [comment] 2016-07-14 11:06
The combined option could be put as a selectable option in settings. I would presume the "combined" feature only benefits a few? It's a nuisance to have it sit in the menu, its being displayed as the default setting when opening AndStatus which assumes users constantly have the option to switch "combined" off or on. Personally I am confused & annoyed by this feature and I wouldn't mind seeing it hidden when "combined"is not used on the app.

**Comment by yvolk** [comment] 2016-07-14 16:39
@bulletbites "Combined" is for everybody having more than one account in AndStatus. It allows to switch less between account. Even if a User needs to turn it on or off seldom, this cannot be put into "Settings".
Retarding unwanted switching to " Combined" timeline - this will be fixed, of course.

How many accounts do _you_ have?

**Comment by yvolk** [comment] 2016-07-15 05:33
As of v.27.03 there are some improvements on this: "Default" timeline opens in many cases where some "Combined" timeline opened earlier.
You can set _any_ timeline as your Default Timeline in the "Manage timelines" view.

**Comment by gjedeer** [comment] 2016-07-18 12:43
Thank you. It's still confusing, though: I was viewing Home feed for account X, which is not my default account. I've pressed Home and clicked on &s icon. I was looking at Friends Combined feed of account X now.

On July 15, 2016 7:33:54 AM CEST, Yuri Volkov <notifications@github.com> wrote:
>As of v.27.03 there are some improvements on this: "Default" timeline
>opens in many cases where some "Combined" timeline opened earlier.
>You can set _any_ timeline as your Default Timeline in the "Manage
>timelines" view.
>
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/andstatus/andstatus/issues/389#issuecomment-232863673

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bulletbites** [comment] 2016-07-19 03:28
@yvolk I have only one active GNU account in AndStatus. When starting AndStatus the default setting for the timeline is "Home combined". Now I tried unticking all the stuff in "Manage timelines" but still it shows  "Home combined". I vaguely get what the feature adds to AndStatus but again I would think the "combined" feature is too prominent for its own good.

**Comment by yvolk** [comment] 2016-07-31 10:42
@bulletbites You have to set your default timeline explicitly. Please open context menu of the timeline in the "Manage timeline" list and select "Default timeline" in the Context menu.

**Comment by bulletbites** [comment] 2016-08-07 19:04
@yvolk holy shit. I was furiously trying to still fix my issues with "Home combined". I finally figured it out!

In "Manage Timelines look if there is a "D" somewhere showing in one of the timelines listed. I totally overlooked this "D". It was showing up in between the column "Displ." and "Title". The "default" will choose that one for your default TL and if it happens to be for instance the timeline "Home combined" this will show up as the default when you start the app up, when you "Go to the Top", refresh or renew the TL.

Once you figure out that that pesky little "D" is the culprit (read the default) you can figure out that you can now set ANY timeline as your default. The issue is resolved and I hope others experiencing similar problems can understand that the solution lies in "setting the little d" in manage timelines. I'll provide screenshots to clarify if this post still confuses people. Anyway, thanks @yvolk for your patience.

**Comment by yvolk** [comment] 2016-08-09 17:01
@bulletbites Maybe I should change default value of the ”Defaul Timeline” to ”Home Timeline of the first account added to AndStatus” ?!

**Comment by bulletbites** [comment] 2016-08-11 20:45
@yvolk in my own case I had trouble understanding how to properly SET my TL stuff. What you are suggesting should already help so that single account users aren't pestered with a TL setting they rather see changed. 

I also wonder how many people actually use the "combined feature". I know what it does but I think most people use AndStatus as THE microblogging app (together with twitter). So 1 app for a Twitter-alternative and one separate app for Twitter (the default twitter app). To be honest I don't understand why people are combining twitter and gnusocial in AndStatus: the posting functionality of twitter gets gimped thru AndStatus.

**Comment by yvolk** [comment] 2016-08-12 16:43
@bulletbites I saw several posts, where people were satisfied exactly with having both Twitter and GNU Social Timelines in one application. I'm with them on this :-)
BTW What AndStatus lacks for you to be used as a Twitter client also?

**Comment by bulletbites** [comment] 2016-08-14 03:45
On a whole I think AndStatus could be cleaner and leaner.

1. Posting: replying/posting should be just like the twitter app does. A new clean posting interface not embedded in the TL but in its own window.
2. Vids/Stats: both are not yet supported by gnu, but still.
3. Instant working buttons below the message. It's flaky at the moment. Often when I press the heart button it does not seem to register it or seems to do it somewhat delayed.
4. Timeline interface: in it's current state I would prefer having NOT to micromanage how and what my TL does, it makes things more confusing and its not always clear how and if it actually does what you expect it to do. 
5. search-icon should NOT be a globe but a looking glass
6. buggyness or is it: A lot of the tickets get opened on github and I think its a combination of people not understanding something and having it set the wrong way or it actually IS a bug and it often becomes a challenge for you to understand, reproduce and hopefully fix the issue.

The confusion problem is also a little bit the main problem with AndStatus. Its heavy on options, heavy on settings and often I don't trust the setting to actually do what I think it would do.

For a dedicated gnusocial app that even comes close to the twitter-app AndStatus is the BEST there is at the moment but if the twitter app would allow for combined/multiple microblogging systems (adding gnusocial to it) I would dump AndStatus in a second, no hesitation. I would prefer it if AndStatus would mimic the twitter app as best as possible without all the quirkiness. 

I often wondered how AndStatus could be improved in respect to ease of use in general. I think a online instructions manual would benefit it greatly. Confused users could look up stuff if they want to set AndStatus up or customize it (like with the manage timelines thingy) and it would make it easier for you too because you could just point them to the manual to resolve the issue at hand. If you consider making a manual I'm sure the community (me included) would be willing to help you with that.

**Comment by yvolk** [comment] 2016-08-15 07:20
Actually combined timeline is needed to combine information gathered from different GNU social instances. As you know, different GNU social instances have different (although partially overlapping) information. This is why I, for example, use several accounts on different GNU Social hosts.
In order to fight with duplicated posts found on different networks I'm implementing ”Collapse duplicated posts” feature, see https://github.com/andstatus/andstatus/issues/337

**Comment by yvolk** [comment] 2016-08-15 16:42
@bulletbites Regarding own window for an Editor please read/look and discuss here: https://github.com/andstatus/andstatus/issues/290

**Comment by yvolk** [comment] 2016-08-15 16:46
> Instant working buttons below the message. It's flaky at the moment. Often when I press the heart button it does not seem to register it or seems to do it somewhat delayed.
We will discuss this in #410

**Comment by yvolk** [comment] 2016-08-15 16:57
> search-icon should NOT be a globe but a looking glass

@bulletbites As you can see, we have _two_ types of Search:
1. Search in local cache only. Quicker and doesn't require Internet connection. This doeas have a common "looking glass" icon.
2. Global Search. The same as above plus querying remote servers via Internet.It reuses another available material icon: Globe. In the old versions of AndStatus I made special icon for this case: combined general Search icon with a Globe. But as we moved to Android team-provided icons I decided that it is too hard for me to draw my custom icon for the "Global search"...

**Comment by yvolk** [comment] 2016-08-15 17:05
> The confusion problem is also a little bit the main problem with AndStatus. Its heavy on options, heavy on settings and often I don't trust the setting to actually do what I think it would do.

I think that we need to use all ways to minimize such a confusion. Currently I see these:
1. Extending User Manual collaboratively: https://github.com/andstatus/andstatus/wiki/AndStatus-User-Manual
2. Choosing better default values so that most of users don't need to change any settings.
3. Breaking settings into Simple and Advanced, as discussed here: https://github.com/andstatus/andstatus/issues/237

**Comment by gjedeer** [comment] 2016-08-19 15:37
I'm not really sure what the posters above are discussing, but the original issue persists as of 27.06: i clicked a link on my home timeline, it opened in firefox, then clicked back, found myself in &s and home timeline has been replaced with my default timeline.

So &s still loses its previous view on resume.

**Comment by yvolk** [comment] 2016-08-19 16:08
@gjedeer I think that the issue title confuses people.
So the problem now is not exactly about ”combined" timeline, but about the Timeline view state persistence?!

**Comment by gjedeer** [comment] 2016-08-19 16:17
Yes, other people hijacked the thread.

On August 19, 2016 6:08:35 PM CEST, Yuri Volkov <notifications@github.com> wrote:
>@gjedeer I think that the issue title confuses people.
>So the problem now is not exactly about ”combined" timeline, but about
>the Timeline view state persistence?!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/andstatus/andstatus/issues/389#issuecomment-241060923

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yvolk** [comment] 2016-08-19 19:17
@gjedeer I just tested both cases: 
rotation and clicking on a link and then returning back to AndStatus;
on two devices: Android 6 2GB RAM and Android 4.4 512 MB RAM (Nexus One)
In both cases AndStatus restored a Timeline (not a default one!) and a position on it.

So I cannot reproduce the problem now... Maybe you have some settings, which force Android System shut down completely applications, which lost focus?! - In that case yes, default timeline will be opened.

**Comment by gjedeer** [comment] 2016-08-19 21:20
Thank you for your answer.

I don't think I have such settings. K-9 Mail, which also reacts poorly to killing (saves edited message to drafts and closes editor), never had any related issues on this phone. It's a 4.4 with 2GB RAM. No task killers too.

So no plans to restore state in onResume?

**Comment by yvolk** [comment] 2016-08-20 03:51
@gjedeer Please understand me correctly: AndStatus _does_ restore its Timeline view state on _resume_, but not on it _creation_. I would like to find out, why it doesn't resume on your device, but I cannot reproduce it.

**Comment by gjedeer** [comment] 2016-08-20 07:31
Got it. 

I've just spent some time trying to reproduce it, happened to me once during a screen flip but i was too slow to hit pause in catlog. My next post will be with logcat, any app create events should be there.

On August 20, 2016 5:51:50 AM CEST, Yuri Volkov <notifications@github.com> wrote:
>@gjedeer Please understand me correctly: AndStatus _does_ restore its
>Timeline view state on _resume_, but not on it _creation_. I would like
>to find out, why it doesn't resume on your device, but I cannot
>reproduce it.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/andstatus/andstatus/issues/389#issuecomment-241176907

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yvolk** [comment] 2016-08-20 12:13
@gjedeer On creating logs in AndStatus see https://github.com/andstatus/andstatus/issues/225

**Closed** 2019-10-14 16:32 UTC
Labels: Could not reproduce, Documentation issue, Questions&Answers, UX issue
