### ISSUE TITLE
Andstatus crashes when I try to add a Twitter account 

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#207] opened 2015-01-17 12:28 UTC
I've been trying to add a Twitter account a several times but I only get a "AndStatus has crashed"

**Comment by yvolk** [comment] 2015-01-17 14:02
Please more details,  when this occurs...

**Comment by moshpirit** [comment] 2015-01-17 14:04
I'm trying to add a new account, right now: 
Setting / add a new account / Twitter / add this account / crash :(

**Comment by yvolk** [comment] 2015-01-18 13:05
I cannot reproduce this. Tried with Android 4.1.2. - added Twitter account without errors (to the fresh installation.

**Comment by moshpirit** [comment] 2015-01-18 13:48
I've got this error:
>Unfortunately, the process org.andstatus.app has stopped.

**Comment by yvolk** [comment] 2015-01-18 13:55
If you connect your device to PC with Android IDE (Eclipse...) you should be able to see a full log including a stack trace, showing statements, where the exception occurred.

**Comment by yvolk** [comment] 2015-01-30 16:53
@moshpirit Any news on this using the latest build?

**Comment by moshpirit** [comment] 2015-01-30 16:55
No, I think you can close this issue :)

**Comment by yvolk** [comment] 2015-01-30 16:56
Closing as no evidence now...

**Closed by yvolk** 2015-01-30 16:56 UTC

**Comment by moshpirit** [comment] 2015-01-30 17:10
Nope, the problem is that AS doesn't let me enter my username and password because it doesn't show these fields.

**Comment by yvolk** [comment] 2015-01-30 17:13
This is how it works: you type username and password after pressing "Add this account" in AndStatus, at Twitter web site.

**Comment by moshpirit** [comment] 2015-01-30 17:14
But I can't type it, there's no place to write :\

**Comment by yvolk** [comment] 2015-01-30 17:15
Does Twitter Web site open?
Post screenshot, please!

**Comment by moshpirit** [comment] 2015-01-30 17:16
Nope, nothing, ok I'll share you one

**Comment by yvolk** [comment] 2015-01-30 17:17
I need a screenshot, which opens after you press "Add this account" button in AndStatus
What's your Android version?
Did you change SSL Security settings?

**Comment by moshpirit** [comment] 2015-01-30 17:23
Screenshot: https://my.owndrive.com/public.php?service=files&t=f9f245d025849d2d1afc7b86493a1be4

When I push "Add this account", AS crashes. 
Using Android 4.3 
No changes in SSL (safe mode and SSL it's enabled by default on Tw)

**Comment by yvolk** [comment] 2015-01-30 17:43
I see this on Android 4.3. emulator after pressing "Add Account" button:
Please provide a a stacktrace to figure out where the problem is...
![addingaccount](https://cloud.githubusercontent.com/assets/207716/5980347/9f258782-a8c0-11e4-9b44-6e990857ae45.png)

**Comment by moshpirit** [comment] 2015-01-30 17:45
What's a stacktrace?

**Comment by yvolk** [comment] 2015-01-30 19:00
A stacktrace is a list of Java code components, which called each other in a sequence to produce some exception. In our case - the crash.
See this crash stacktrace, which I easily fixed, receiving it:
![stacktrace](https://cloud.githubusercontent.com/assets/207716/5981415/1b0d5046-a8cb-11e4-8281-cd0b8eb5ad9e.png)
As you can see, the stacktrace shows line members and module names, where execution passed...

**Comment by rodneyrod** [comment] 2016-07-21 12:20
Getting this issue too, but it only occurs when trying to add a second Twitter account.

As soon as you click on the field to enter your username, the whole app crashes. Clicking and entering text in the password field has no effect.
