### ISSUE TITLE
Crash during downloading large pictures 

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#179] opened 2014-11-30 12:23 UTC
Sometimes, Andstatus crashes when it tries to download pictures like [this one]( https://identi.ca/krugor/image/x6hAn3XTRqC5LAUZRfkVSw). I think it's necessary to implement an option (checked by default) which allows to download resized pictures to a smaller size.
The same uploading: if we use 3G, it should be better to upload a picture in a smaller size than if we do it using WiFi or just for making it faster.
Maybe sync options should be a good place to add these configurations.

**Comment by moshpirit** [comment] 2015-01-17 03:39
It still happens and I think it should be implemented, maybe Twidere could be a good rely.

**Comment by yvolk** [comment] 2015-01-17 13:41
I will add some switch to choose smaller size images from a server (if a server pprovides such an option). E.g. downloading thumbnail...
Meanwhile please try these ways:
1. Turn off "Sync while using application" option. 
2. Turn on "Log network level messages" and "Log everything to file". Then send me recent logs after a crash.

**Comment by moshpirit** [comment] 2015-01-18 14:00
1. It's already disabled
2. I'ts already enabled

I'll send you the file to your email!

**Comment by yvolk** [comment] 2015-01-24 05:03
I could reproduce the bug by showing the below mentioned notice:
@andstatus 14.0. Now on 14.1 it crashes for instance when displaying my post with image: https://quitter.se/notice/3289953 Will logcat later
-- 
netmackan

**Comment by netmackan** [comment] 2015-01-25 09:59
I'm sorry to report that even with the upgrade to 14.2 (from f-droid) I still have the crash on my post with image (https://quitter.se/notice/3289953). I'll try to get the stacktrace.

**Comment by moshpirit** [comment] 2015-01-25 10:01
Mm bad to know :(
Btw, wrong image

**Comment by yvolk** [comment] 2015-01-25 10:02
This fix was done after v.14.2. It may be tested only compiling the code from this repository. (See this instruction: https://github.com/andstatus/andstatus/wiki/Building-AndStatus-from-Source-code-on-your-Android-device-using-AIDE-application

Will be released in v.14.3

**Comment by netmackan** [comment] 2015-01-25 10:26
Oh sorry, that explains it :)

I don't use Google Play and in addition AIDE seems to be a non-free software proprietary app.  I'll try to build from source the conventional way instead.

**Comment by netmackan** [comment] 2015-01-25 11:25
I have now built with the latest on master and it works great! The image is displayed and everything. Big thanks!

**Closed** 2015-02-01 05:40 UTC
