### ISSUE TITLE
Will not interact with Twitter

### ISSUE THREAD

**Issue by EricxDu** [andstatus/andstatus#421] opened 2016-09-26 18:47 UTC
A while back AndStatus stopped being able to post replies, retweets, or favorites to twitter. log of most recent error follows.

R; Retweet , foreground for ericxdu23/Twitter
Created 26 minutes ago
executed:2, last:6 minutes ago, retriesLeft:8, error:Soft,  
Reblog 776223010059583489, 
Status code=UNKNOWN; soft; 
; url:'https://api.twitter.com/1.1/statuses/retweet/776223010059583489.json'; authenticated; 
Caused by cz.msebera.android.httpclient.client.HttpResponseException: Forbidden, 
CommandExecutionContext:{MyAccount:{accountName:ericxdu23/Twitter,id:3,oid:3320186221,OAuth,credentialsPresent,syncFrequency:14400,syncable,syncauto}, CommandData:{command:reblog,foreground,created:20 minutes ago,Timeline{ericxdu23/Twitter, type:home, userId:3},itemId:17793,hashCode:1158652859,CommandResult:{executed:1, last:20 minutes ago, retriesLeft:9, error:Soft}}}

**Comment by yvolk** [comment] 2016-09-26 19:02
This is a duplicate of #415. Please continue investigation/discussion there

**Closed by yvolk** 2016-09-26 19:02 UTC
Labels: Duplicate
