### ISSUE TITLE
pump.io: AndStatus creates unintuitive "followed" activities

### ISSUE THREAD

**Issue by clacke** [andstatus/andstatus#425] opened 2016-10-22 06:33 UTC
As can be seen in [a capture of my pump stream](https://archive.is/fEcVr#selection-2393.0-2395.40), AndStatus creates activities like "Claes Wallin (韋嘉誠) followed an unknown object type: 170202".

The expected activity is e.g. "Claes Wallin (韋嘉誠) followed _Person's name, link to profile page_".

**Comment by clacke** [comment] 2016-10-22 06:45
Or might this be related to https://github.com/pump-io/pump.io/issues/1216 ?

**Comment by yvolk** [comment] 2016-10-22 09:02
@clacke Thank you for noticing. Following your report I took time to find out, whose messages in Pump.io and why I get in my timeline.
This looks like there was some bug/data failure in Pump.io, but currently I was able to follow/unfollow Pump.io users via AndStatus. And as you noted, in order to fix my follows I had to:
1. "Follow" via Web Pump.io interface a person, whose messages I received constantly (without following...). 
2. Unfollow then follow again people, who were marked as Followed by me, but whose messages I didn't receive for a long time.

I see via Web interface: "AndStatus@Identi.ca followed EVAnaRkISTO"

After this I saw him as "following by andstatus@identi.ca" in AndStatus and could "Unfollow".

I see via Web interface: "AndStatus@Identi.ca stopped following EVAnaRkISTO"

Then I successfully Followed another user via AndStatus: 

I see via Web interface: "AndStatus@Identi.ca followed JanKusanagi"

Then I went to a list of people, whom I follow: https://identi.ca/andstatus/following - I fould out that I didn't receive their messages for a long time. I unfollowed/followed them again via web interface...

**Comment by yvolk** [comment] 2016-10-22 09:35
There is definitely something wrong with Pump.io: At identi.ca I see that now I follow sazius@pump.saz.im, but when I go to his site: https://pump.saz.im/sazius and Log in there, I still see "Follow" button, as if I don't follow him. Pressing that button gives some "Internal error"...

**Comment by jankusanagi** [comment] 2016-10-22 13:03
I'd like to point out that I've never seen this type of "broken activities" created by any other client.
The closest thing would be a "JaneDoe followed a person", which happens when trying to follow a wrong ID, such as "invented-does-not-exist@nonexistantserver.lalala". That's easy to reproduce.

@clacke, could we know who you were trying to follow when those activities were created?

@yvolk, is there a way he could get the JSON sent by AndStatus when those activities happen?

**Comment by yvolk** [comment] 2016-10-22 13:06
@jankusanagi I couldn't reproduce such erroneous activities that @clacke noticed: as I wrote above, all Follow/Unfollow activities, sent by AndStatus, looked normally via web UI at identi.ca

**Comment by clacke** [comment] 2016-10-22 14:41
As the activities only say "Followed unknown xyz" I actually don't know whom I was trying to follow. And my `.../following` is broken as seen in pump-io/pump.io#1216, so I can't check. :-/

I will try and see if maybe I was following some recent followers back.

**Closed** 2020-06-02 05:01 UTC
Labels: Third party issue
