### ISSUE TITLE
Cannot add Friendica account anymore. 

### ISSUE THREAD

**Issue by kr428** [andstatus/andstatus#569] opened 2023-01-12 18:12 UTC
59.15 from fdroid seems to have issues adding Friendica 2022.12 accounts. Chose Mastodon, entered my instance name (loma.ml) and ended up with "entity could not be processed". Known problem?

![Screenshot_20230112-191022_AndStatus](https://user-images.githubusercontent.com/685879/212145741-67fe0f65-6519-4aab-96e6-1f50dbae760d.jpg)

**Comment by yvolk** [comment] 2023-01-12 19:34
@kr428 Please check if this problem is caused by an upgrade. Previous versions may be downloaded e.g. from history of changes here: https://github.com/andstatus/andstatus/issues/456

**Comment by yvolk** [comment] 2023-01-12 19:42
I just checked if adding an account at mastodon.social works with current code: yes, it does.
So this looks like a problem that may need friendica developers for a fix.

**Comment by kr428** [comment] 2023-01-12 20:06
@yvolk I downgraded to 59.10, re-added the account - which worked - and upgraded to 59.15 afterwards - which left it working, on the same Friendica instance. So it feels like this is somehow related to changes in between 59.10 and 59.15 for the initial signup / auth procedere? Any info I can provide to debug this?

**Comment by yvolk** [comment] 2023-01-13 06:52
@kr428 The problem is probably related to this improvement of compatibility with OAuth 2.0 specification. That fix may affect services that followed Mastodon's implementation instead. See https://github.com/andstatus/andstatus/issues/561
Please note that even after this change AndStatus still can successfully add an account at Mastodon instance (I tested this yesterday at mastodon.social ).
Please read that thread with our notes on testing.

In order for me look at this, I need to have a test account at the Friendica server having the latest development version. Could you provide such an account for me?

**Comment by kr428** [comment] 2023-01-13 07:10
Trying to ping @annando here. I _think_ squeet.me runs latest development version of Friendica; maybe however (looking at #561) this might require changes in Friendica as well?

**Comment by annando** [comment] 2023-01-13 07:37
Squeet.me is on dev, but not the current one.

**Comment by yvolk** [comment] 2023-01-13 10:15
@kr428 
> this might require changes in Friendica as well?
Maybe this will be Friendica-side change only...

@annando

**Comment by yvolk** [comment] 2023-01-13 18:48
Hi @annando , I checked Squeet.me and I don't see any registration link there.
Anyway, I tried to log into squeet.me, and got similar response from a server as @kr428 there during opening authorization web page:
1. AndStatus opens the web page: 
```
https://squeet.me/oauth/authorize?response_type=code&client_id=62149b5c194dff7b20644d36599624386475b9efb668bf5bb08fed0c3235ca63&redirect_uri=http%3A%2F%2Foauth-redirect.andstatus.org&scope=read%20write%20follow&state=state_65_1673634926129
```
and instead of an HTML response gets this:
```
{
    "error": "Unprocessable Entity"
}
```

Probably this is caused by addition of "client_id" to the Access Token Request as required by OAuth 2.0 spec, see my comment https://github.com/andstatus/andstatus/issues/561#issuecomment-1355571970

Friendica code should be adapted to handle this normally as this conforms to the spec.

**Comment by yvolk** [comment] 2023-01-14 06:19
> BTW: I just saw that you still has got a test account on my machine that I use for developing: pirati.ca.

Yes, I tried pirati.ca yesterday also. Didn't remember that it is also yours :-)
I my old AndStatus setup Pirati.ca is still "GnuSocial" type of social network... tried now and got that even your old profile there currently is mapped to some other person... (consequence of using numbers as local users' IDs...)

**Comment by annando** [comment] 2023-01-14 13:37
I try to work on it this weekend. So possibly you can even test it before I created the PR.

**Comment by annando** [comment] 2023-01-14 18:39
I just saw that on creating the app the `redirect_uris` is transmitted as array. Currently we only support a string here.

**Comment by yvolk** [comment] 2023-01-15 13:52
@annando Thank you for information.
Regarding Client registration please see https://github.com/andstatus/andstatus/issues/561#issuecomment-1356223928
Currently AndStatus makes up to two attempts to register:
1. OAuth 2.0 - compliant (see https://www.rfc-editor.org/rfc/rfc7591#section-3.1 )  - please see that "redirect_uris" IS an array according to the spec.
2. If the registration fails, AndStatus makes the second attempt, this time - with a hack for Mastodon.

See the metadata for these attempts: https://github.com/andstatus/andstatus/blob/17891408454e06c27ea8539e27ee729c9a1a2d86/app/src/main/kotlin/org/andstatus/app/net/http/HttpConnectionOAuth2.kt#L96

**Comment by yvolk** [comment] 2023-01-15 13:58
@annando I would suggest for Friendica to support standard OAuth 2.0 also, not only Mastodon's custom variant.
OR fail at the first attempt (as Mastodon itself does)

**Comment by annando** [comment] 2023-01-15 23:10
What about the missing `client_secret` upon requesting the token?

**Comment by yvolk** [comment] 2023-01-16 05:14
@annando 
I see that Access Token Request (POST) to https://pirati.ca/oauth/token does have "client_id" body parameter yet the sever responds with 401 Unauthorized.

**Comment by yvolk** [comment] 2023-01-16 05:20
Probably your OAuth 2.0 implementation fails due to absence of client_secret?! As was noted here: https://github.com/andstatus/andstatus/issues/561#issuecomment-1354596980

> that's weird, it looks like Mastodon token endpoints require both client_id and client_secret: https://docs.joinmastodon.org/methods/oauth/#token

I think we better not add client_secret here bacause it's not even an optional parameter, see https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3

**Comment by annando** [comment] 2023-01-22 11:16
Concerning the `client_secret` I found this: https://www.oauth.com/oauth2-servers/access-tokens/authorization-code-request/
> If the client was issued a client secret, then the server must authenticate the client. One way to authenticate the client is to accept another parameter in this request, client_secret. Alternately the authorization server can use HTTP Basic Auth. 

and: https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/
> The client needs to authenticate themselves for this request. Typically the service will allow either additional request parameters client_id and client_secret, or accept the client ID and secret in the HTTP Basic auth header.

So for me it seems as if the `client_secret` has to be provided all the time.

**Comment by yvolk** [comment] 2023-01-22 13:30
@annando Aha-ha :-) I've started to remember that we had similar discussions some time ago... And yes, I see that you and me discussed exactly the same thing two years ago :-)
Please look here: https://github.com/andstatus/andstatus/issues/537

**Comment by annando** [comment] 2023-01-22 13:55
AFAIK that discussion had been about where to fetch these values, see the code here:
https://github.com/friendica/friendica/blob/develop/src/Module/OAuth/Token.php#L56-L72

**Comment by yvolk** [comment] 2023-01-22 14:09
I see where I think the bug is. From your code:
```
if (empty($request['client_id']) && substr($authorization, 0, 6) == 'Basic ') {
```
Since recently AndStatus started to post client_id in the request body of the "Access Token Request", which is allowed according to the specification. But I see that your code, seeing this "client_id" in the body, doesn't even try to look in the header,  where both client_id and client_secret, I think, are still present (I didn't change that).

**Comment by annando** [comment] 2023-01-23 07:26
The PR is merged. It should work now again.

**Comment by yvolk** [comment] 2023-01-24 05:40
I tested that I can add an account at pirati.ca (as a Mastodon Social Network). And can post...
Thank you, @annando !

**Closed by yvolk** 2023-01-24 05:40 UTC
