### ISSUE TITLE
No difference between Reposted and Marked as Favourite on GNU social

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#205] opened 2015-01-03 21:33 UTC
It's just appears like the original post, but nothing more.

E.g. [This note](https://status.vinilox.eu/notice/3096017) has been marked as favourite, but AndStatus just show me the original message, not something like "Gilbert has marked as favourite: [@]gilbert pues helados veganos hay unos pocos xD mira en dimension vegana y creativegan ;-)"

**Comment by yvolk** [comment] 2015-01-04 08:58
This is a GNU social bug.
Duplicate of #200

**Closed by yvolk** 2015-01-04 08:58 UTC

**Comment by moshpirit** [comment] 2015-01-04 09:00
Sorry for de duplicate, but if this is a GNU social bug, why qvitter difference them? I say it to report the bug or not.

**Comment by moshpirit** [comment] 2015-01-04 09:02
In fact, it was notified before as: /username has marked your note as favourite: /note.

**Comment by yvolk** [comment] 2015-01-04 09:32
Let's discuss this in #200...
