### ISSUE TITLE
compress pictures before sending them

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#341] opened 2016-03-02 15:46 UTC
I'm trying to post a picture and seems impossible and I think that it's because of this. 

Here's the log:

R; Publicar "Mirad lo que encontré ayer entre la…"
Creado hace una hora
executed:5, last:hace 25 segundos, retriesLeft:9, error:Soft,  
updateStatus; text:'Mirad lo que encontré ayer entre la col…'; uri:'content://org.andstatus.app.data.FileProvider/downloadfile/1456831206704_7', 
Status code=UNKNOWN; soft; 
; url:'https://quitter.es/api/statuses/update.json'; authenticated; posted:'{"status":"Mirad lo que encontré ayer entre la colección de discos de mi tío :)","source":"AndStatus","media_part_name":"media","media_part_uri":"content:\/\/org.andstatus.app.data.FileProvider\/downloadfile\/1456831206704_7"}'; 
 by javax.net.ssl.SSLException: Write error: ssl=0xb8bf3a50: I/O error during system call, Broken pipe, 
moshpirit/Quitter.Espana,

Even if this error is not caused by the size of the picture, I think it would be nice the feature :)

**Comment by yvolk** [comment] 2016-03-02 16:45
@moshpirit I think that you want a picture to be resized?!
See #324

**Comment by moshpirit** [comment] 2016-03-02 20:07
Hahaha yeah, cool! You always a step above the rest :)

**Comment by yvolk** [comment] 2016-03-02 20:15
Closing as a duplicate of #324

**Closed by yvolk** 2016-03-02 20:15 UTC
