### ISSUE TITLE
Timeline randomly jumping back 5-10% while swiping down

### ISSUE THREAD

**Issue by bentolor** [andstatus/andstatus#342] opened 2016-03-02 16:02 UTC
First of all: Thank you very much for this great piece of software!

I think since v.22.17 I experience a rather annoyingly behavior: On swiping down, the timeline randomly jumps back for 5-10% of the screen. Please see the attached AniGIF for illustration.

This is not due to loading inline gifs (I switched to 3G for demonstration; attachments are only downloaded via WLAN). Probably a side-effect of the new caching logic?

![andtstatus-bug-2](https://cloud.githubusercontent.com/assets/588260/13465971/45d63fe4-e098-11e5-927d-ae13423d8c71.gif)

**Comment by yvolk** [comment] 2016-03-02 16:57
Hi @bentolor, 
Unfortunately, animation that you provided, doesn't allow me to understand, where is a beginning, where you scroll by a finger, and where AndStatus scrolls automatically :-(
Anyway I think that you noticed a behavior that is present for a long time:
AndStatus updates the timeline list in a background, but when it replaces old view with an old one, it positions the new listView to the _top_ of the same item (message) you saw in the old list view. This results in some scrolling up.
So far I was lazy to store and restore position more precisely :-)
For now you could disable in AndStatus Settings -> Timeline -> "Refresh timeline automatically"
?!

**Comment by bentolor** [comment] 2016-03-02 17:07
Hello @yvolk 

No – this is not the "freezing" one would experience due to the _"Refresh timeline automatically"_ nor is this effect present since a long time. In fact I think it was introduced with the latest two releases.

Let me explain the video above: In this video you see how I stroke *three* times from top to bottom. You should also notice i.e. when the Docker image appears or the linuxfoundation post with the desktop the **timeline suddenly jumps** back. **This is not due to a interaction nor to a background update!**

As you can see it happens nearly every hand full of tweets.

Was I able to explain the issue?

**Comment by alanz** [comment] 2016-03-02 18:24
I have also seen this, and reported it via email, it started with 22.17, as a definite change to the UI experience.

It does seem to be related to loading the timeline, if I go back to a fully loaded/seen timeline, it scrolls smoothly.

**Comment by yvolk** [comment] 2016-03-02 19:33
@bentolor I see that I understood you correctly and explained why this happens. The behaviour looks different that it was earlier, because image loading now is done in a background and it doesn't prevent smooth scrolling...

**Comment by yvolk** [comment] 2016-03-02 19:39
I just tested on my device and saw something like this one time: when AndStatus changes ols timeline with updated one it repositions the new timeline not precisely to the place previous one was at the moment of this change, but to some "rounded" position.
I see, in this case this is not about Refreshing timeline due to new updates: this time this is due to loading of the new "page" of a timeline (each page has up to 100 messages).

**Comment by bentolor** [comment] 2016-03-02 19:53
Yes, I you latest observation seems to fit my issue currently the best: It's seems to be not related to online/network loads but to "page" loads from disk.

Strangely the interval seems to be smaller than 100 for me. But the repositioning you described  would perfectly explain the effect.

**Comment by bentolor** [comment] 2016-03-02 20:10
One more thing: Like @alanz wrote: If I start in the middle of a timeline which was already fully displayed, everything scrolls fine & smooth _except_ very short interrupts/offsets probably every 100 tweets.

When I regularly check for new tweets (~35 new tweets), the interval seems to be much smaller (every 10-15 tweets) as you can see in the AniGIF.

**Comment by yvolk** [comment] 2016-03-02 20:20
First page is loaded so that about 10 messages are below and up to 90 - above...
I will try to improve loading logic and positioning...

**Comment by yvolk** [comment] 2016-03-12 08:11
@bentolor Yesterday I encountered a defect similar to what you showed in a gif animation. It appeared that timeline jumping is caused by a broken image file (in this case this was an HTML file instead of .png).
I improved application's behaviour in such cases: now timeline scrolls without "jumps".
Will be released in v.23.02+

**Comment by yvolk** [comment] 2016-03-13 04:25
To improve timeline scrolling smoothness even more we need to know image dimensions before its actual loading from a file to a Timeline. Currently blank image of the same form is set for every image not found in a cache, and it is replaced by an actual image after asynchronous loading to cache.
Switch from image of one form to an image of another form causes noticeable "jumping", although not as bad as we observed at the top of this discussion.
Knowing dimensions will allow us to create blank image of the same size on the fly so that replacing it with a real image will not change timeline view height and hence will not cause "jumping".

**Comment by alanz** [comment] 2016-03-13 10:55
I can report that the scrolling is much better with 23.03. 

There are still minor jumps, but I think that is the unknown image size problem, and the focal point does not move which is the main thing

**Comment by yvolk** [comment] 2016-03-13 12:33
@alanz Thank you for testing this!

**Comment by bentolor** [comment] 2016-03-14 16:49
Looking very forward to test a new versio: Is it enought to run a gradle command to build an up-to-date APK? 

Regarding the image hypothesis: I can confirm that without WLAN / image loading enabled I do not observe the severe jumps as illustrated in the initial report. Very keen to see, if these two changes solve the issue.

Thank you very much, @yvolk for working on this issue!

**Comment by yvolk** [comment] 2016-03-14 18:56
If you're interested in the current state of the application and ready to see something partially implemented/partially working, yes you can always build it from the latest commit, 
but this will not be the latest Beta :-)
Anyway, I'm promoting 23.03 to Production and Adding the 23.03-Release tag for it.

**Comment by bentolor** [comment] 2016-03-16 15:03
Just installed 23.03 and indeed the "jumping" is much better!

So much better, that I get more distracted by this new effect: It seems that the image loading is triggered by the moment, when the tweet becomes visible. Obviously my device is not fast enough so I see the tweet without the image and suddenly the image appears in upper area and shifts the upper part of the screen. This has some distracting "flashing" effect though now the scroll position seems to stay more or less in sync with my thumb.

Would it be possible to shift this triggering of the in-place replacing of the placeholder with the image into the offscreen area, to avoid that we are able to see the image replacement "flash"?

**Comment by yvolk** [comment] 2016-03-16 16:07
This is how Android stock list view works: it decides, when to request new item.
I could predict, which item could be requested next, and start loading to cache a bit earlier...

**Comment by bentolor** [comment] 2016-03-16 16:18
Interesting. I would have assumed that it's a common use-case to lazy load list items _prior_ that they become visible.  

So currently andstatus uses the image dimensions only for the total height calculation? Because I did not see any placeholder image.

**Comment by yvolk** [comment] 2016-03-16 19:19
As I wrote above, currently AndStatus doesn't know dimensions of an image before it's loaded to cache from a file. This is why you still see some shift, when an image replaces transparent placeholder of some average height,,,

**Comment by yvolk** [comment] 2016-03-25 17:13
@bentolor As suggested here:  http://stackoverflow.com/questions/11696584/displaying-photos-in-a-listview-how-to-get-adapter-to-preload-before-users-can
we can preload a couple of images beforehand... The problem to solve is synchronization of asynchronous image loading with views, were these images may be inserted, if a user will continue to scroll in the same direction...

**Comment by yvolk** [comment] 2016-03-25 17:19
Solution than I want to try to get rid of a timeline jumps completely: 
images, which are loaded asynchronously, should have on the screen the same predefined height no matter what their actual size is. I.e. the should be shown with the same height as a blank image that was placed initially in a view.

**Comment by bentolor** [comment] 2016-03-30 08:41
It turns out for me, that the jumps a still present. As far as I understood the mechanics according to your explanations I think the solution you proposed to have a fixed, predefined height has some drawbacks but seems to be the most simple & reliable approach to fix this issue.

Do you plan to crop or to scale down images to keep them within the initial, fixed height?

**Comment by yvolk** [comment] 2016-03-30 16:37
I already implemented this solution and it is available in v.24.03.
Images are scaled.
So far this new approach works as expected on Android 4.4 and 5.1
On my third device with Android 6.0 it works differently, but jumping in not bad also...

Please test!

**Comment by bentolor** [comment] 2016-03-30 17:05
Thank you @yvolk ! I just downloaded & tested the new version.

The good news: the intermittent jump seem to have completely disappeared. 
The down side: I see quite a bunch of really awkward sized image tweets with empty borders filling up the full screen:

![2016-03-30-18-51-45](https://cloud.githubusercontent.com/assets/588260/14150438/4ecab8a6-f6a9-11e5-9660-0dc2ab6ec649.png)

The thing I'm really puzzled about is, that after scrolling by these tweets and the scrolling back, the awkward border has completely disappeared! The image is properly layouted and no intermittent jumping has happened?! 

So obviously the height is somehow adjusted/fixed off-screen, no?

![2016-03-30-18-52-25](https://cloud.githubusercontent.com/assets/588260/14150459/63689e0e-f6a9-11e5-8881-505fff782c70.png)

My proposals:
- Maybe a better fit for the fixed _»i dont know the exact dimension«_-height would be a quadratic box, no? (Same height as width)
- How does the off-screen "height fixing" work? Is it possible to adjust the levels so that it becomes more likely that new images are already displayed with the correct height on the first render? I got the impression that scrolling down slowly for new tweets can avoid these akwards borders, and scrolling very fast provokes them?

**Comment by yvolk** [comment] 2016-03-31 06:00
Currently blank image for portrait device orientation has also portrait orientation. This is good when you see images with portrait orientation and this produces large blank space for landscape images, as you see.
Current successful fix of the image height in a list proved that approach with blank image works. Blank image is used only in a case when requested image is not loaded (from SD) into an in-memory cache. This is why on a second scroll over the same images you see them without any unnecessary blank space: images are loaded from cache synchronously.

I see that proper solution is to find out actual image dimensions beforehand, so we could reserve correct space for each image. Stay turned! :-)

**Comment by yvolk** [comment] 2016-04-04 05:56
A note for implementation: using AsyncDrawable as per: http://developer.android.com/training/displaying-bitmaps/display-bitmap.html

**Comment by yvolk** [comment] 2016-04-09 08:21
@bentolor Attached images preload implemented for Timeline. This allows to avoid most of the time unnecessary blank spaces. Will be released in v.25+

**Comment by yvolk** [comment] 2016-04-10 06:06
Implemented in v.25.01 and published at the Open Beta Testing channel: https://play.google.com/apps/testing/org.andstatus.app

**Comment by bentolor** [comment] 2016-04-11 15:54
I'm using AndStatus via F-Droid. To test the beta I just uninstalled and reinstalled AndStatus via Play. Unfortunately it directly dies on startup with an `OutOfMemoryError` in `BitmapFactory.java`. 

As I had to deinstall the previous version I assume there should be no leftovers.

**Comment by yvolk** [comment] 2016-04-11 16:06
@bentolor Interesting, was you prompted to send Crash Report? Please do this in order the problem to be fixed.
BTW , I personally tested this even on 6 years old Nexus One - No OutOfMemory...

**Comment by bentolor** [comment] 2016-04-11 19:27
@yvolk Thanks for you feedback. Just sent you the crash report. Do the Play build and the F-Droid build differ? I have some Google services disabled on my device and with 2GB of RAM it also doubt that "memory" is the issue.

By the way: Google play rates AndStatus for adults only? (FSK18 equal to X-rated). This must be wrong, no?

**Comment by yvolk** [comment] 2016-04-11 19:47
Thank you @bentolor.  F-Droid has different build of the same source code, but it does this build only after I mark release is this repo...
It looks like in the latest build of AndStatus I hit some library compatibility problem. Trying to solve it...

**Comment by yvolk** [comment] 2016-04-13 08:15
@bentolor Please try v.25.03 in Beta. It has specific fixes for Android v.4 devices.

**Comment by bentolor** [comment] 2016-04-13 08:46
Thanks you @yvolk  Now it works!
New behavior looks good: Images fit nicely into the tweet. Very rarely I see single images with an empty borders. Not sure about potentially missing images. Will test during my daily work and report back on issues.

**Comment by alanz** [comment] 2016-04-13 09:10
I just installed v.25.03 (170) on my OnePlus. When a launch it, the screen goes black for a few seconds then the app terminates

**Comment by bentolor** [comment] 2016-04-14 08:02
v.25.03 stopped working for me. No updates & error message on UI. 

Logfile reports about `UNAUTHORIZED`. Seems AndStatus lost the Authorization info? 

Uninstalling v.25.03, reinstalling v24.x from F-Droid and using the same Backup for account recovery seems to work?!

```
2016-04-14-08-54-06 D/TlsSniSocketFactory: Using documented SNI with host name api.twitter.com
2016-04-14-08-54-06 I/TlsSniSocketFactory: Established TLSv1.2 connection with api.twitter.com using TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
2016-04-14-08-54-06 V/I18n: '{"errors":[{"code":32,"message":"Could…' max=40
2016-04-14-08-54-06 E/CommandExecutorLoadTimeline: Load Timeline,
Status code=UNAUTHORIZED; hard;
statusLine:'HTTP/1.1 401 Authorization Required'; statusLine:'HTTP/1.1 401 Authorization Required'; statusCode:UNAUTHORIZED (401); url:'https://api.twitter.com/1.1/direct_messages.json?since_id=696740068975906823&count=200&user_id=2222222222'; authenticated; response:'{"errors":[{"code":32,"message":"Could…'; error='?',
bentolor/Twitter, timeline:direct, userId:1,
2016-04-14-08-54-06 D/OAuthClientKeys: Loaded OAuthClientKeysSecret; Keys present
2016-04-14-08-54-06 V/HttpConnectionOAuthApache: Credentials presence: clientKeys:true; userKeys:false,false
2016-04-14-08-54-06 V/MyServiceEventsBroadcaster: state:RUNNING, event:AFTER_EXECUTING_COMMAND, Direktnachrichten für bentolor
2016-04-14-08-54-06 V/MyServiceEventsReceiver: onReceive AFTER_EXECUTING_COMMAND for SyncAdapter, instanceId:113
2016-04-14-08-54-06 V/MyServiceManager: Created, instanceId=123
2016-04-14-08-54-06 V/MyContextHolder: Already initialized by TimelineActivity (called by: org.andstatus.app.service.MyServiceManager@442427e0)
2016-04-14-08-54-06 D/MyServiceManager: Notification received: Service state=RUNNING
2016-04-14-08-54-06 V/CommandExecutorLoadTimeline: ExecutedStep CommandExecutionContext:{MyAccount:{accountName:bentolor/Twitter,id:1,oid:2222222222,OAuth,credentialsPresent,syncFrequency:1800,syncable,syncauto},timeline:direct,userId:1,CommandData:{command:automatic-update,timeline:direct,step,created:vor 22 Stunden,account:bentolor/Twitter,hashCode:-1630075402,CommandResult:{error:Hard,
Load Timeline,
Status code=UNAUTHORIZED; hard;
statusLine:'HTTP/1.1 401 Authorization Required'; statusLine:'HTTP/1.1 401 Authorization Required'; statusCode:UNAUTHORIZED (401); url:'https://api.twitter.com/1.1/direct_messages.json?since_id=696740068975906823&count=200&user_id=2222222222'; authenticated; response:'{"errors":[{"code":32,"message":"Could…'; error='?',
bentolor/Twitter, timeline:direct, userId:1}}}
2016-04-14-08-54-06 D/CommandExecutorLoadAllTimelines: Executed CommandExecutionContext:{MyAccount:{accountName:bentolor/Twitter,id:1,oid:2222222222,OAuth,credentialsPresent,syncFrequency:1800,syncable,syncauto},timeline:direct,userId:1,CommandData:{command:automatic-update,timeline:all,created:vor 22 Stunden,account:bentolor/Twitter,hashCode:997383998,CommandResult:{executed:30, last:gerade eben, error:Hard,
Load Timeline,
Status code=UNAUTHORIZED; hard;
statusLine:'HTTP/1.1 401 Authorization Required'; statusLine:'HTTP/1.1 401 Authorization Required'; statusCode:UNAUTHORIZED (401); url:'https://api.twitter.com/1.1/statuses/home_timeline.json?since_id=720165619728039937&count=200&user_id=2222222222'; authenticated; response:'{"errors":[{"code":32,"message":"Could…'; error='?',
bentolor/Twitter, timeline:home, userId:1, ;
Load Timeline,
Status code=UNAUTHORIZED; hard;
statusLine:'HTTP/1.1 401 Authorization Required'; statusLine:'HTTP/1.1 401 Authorization Required'; statusCode:UNAUTHORIZED (401); url:'https://api.twitter.com/1.1/statuses/mentions_timeline.json?since_id=701039673519579136&count=200&user_id=2222222222'; authenticated; response:'{"errors":[{"code":32,"message":"Could…'; error='?',
bentolor/Twitter, timeline:mentions, userId:1, ;
Load Timeline,
Status code=UNAUTHORIZED; hard;
statusLine:'HTTP/1.1 401 Authorization Required'; statusLine:'HTTP/1.1 401 Authorization Required'; statusCode:UNAUTHORIZED (401); url:'https://api.twitter.com/1.1/direct_messages.json?since_id=696740068975906823&count=200&user_id=2222222222'; authenticated; response:'{"errors":[{"code":32,"message":"Could…'; error='?',
bentolor/Twitter, timeline:direct, userId:1}}}
2016-04-14-08-54-06 D/OAuthClientKeys: Loaded OAuthClientKeysSecret; Keys present
2016-04-14-08-54-06 V/HttpConnectionOAuthApache: Credentials presence: clientKeys:true; userKeys:false,false
2016-04-14-08-54-06 V/MyServiceEventsBroadcaster: state:RUNNING, event:AFTER_EXECUTING_COMMAND, Alle für bentolor
2016-04-14-08-54-06 V/MyServiceEventsReceiver: onReceive AFTER_EXECUTING_COMMAND for SyncAdapter, instanceId:113
2016-04-14-08-54-06 V/SyncAdapter: onReceive; command:AUTOMATIC_UPDATE
2016-04-14-08-54-06 V/SyncAdapter: onPerformSync; Ended, has error
2016-04-14-08-54-06 V/MyServiceManager: Created, instanceId=124
2016-04-14-08-54-06 V/MyContextHolder: Already initialized by TimelineActivity (called by: org.andstatus.app.service.MyServiceManager@44526d10)
2016-04-14-08-54-06 V/QueueExecutor: Polled in background null
2016-04-14-08-54-06 D/MyServiceManager: Notification received: Service state=RUNNING
2016-04-14-08-54-06 D/QueueExecutor: Ended, No more commands, 0 commands left
2016-04-14-08-54-06 V/QueueExecutor: onPostExecute
2016-04-14-08-54-06 V/MyService: setIsStopping Stopping; startId=1; queue is empty
2016-04-14-08-54-06 V/MyService: setIsStopping Continuing stopping; startId=1; queue is empty
2016-04-14-08-54-06 V/MyService: couldStopExecutor;  Removing Executor QueueExecutor:{stopping, org.andstatus.app.service.MyService$QueueExecutor on SYNC; age 2sec; FINISHING 0sec ago; instanceId=115; org.andstatus.app.service.MyService$QueueExecutor@c2d3c654}
2016-04-14-08-54-06 V/MyService: saveQueue-to-ERROR; Command saved: CommandData:{command:fetch-timeline,timeline:home,created:vor 8 Stunden,hashCode:17033462,CommandResult:{executed:9, last:vor zwei Stunden, error:Hard,
Load Timeline,
Status code=UNAUTHORIZED; hard;
statusLine:'HTTP/1.1 401 Authorization Required'; statusLine:'HTTP/1.1 401 Authorization Required'; statusCode:UNAUTHORIZED (401); url:'https://api.twitter.com/1.1/statuses/home_timeline.json?since_id=720165619728039937&count=200&user_id=2222222222'; authenticated; response:'{"errors":[{"code":32,"message":"Could…'; error='?',
bentolor/Twitter, timeline:home, userId:1, ;
Load Timeline,
...
Status code=UNAUTHORIZED; hard;
statusLine:'HTTP/1.1 401 Authorization Required'; statusLine:'HTTP/1.1 401 Authorization Required'; statusCode:UNAUTHORIZED (401); url:'https://api.twitter.com/1.1/statuses/home_timeline.json?since_id=720165619728039937&count=200&user_id=2222222222'; authenticated; response:'{"errors":[{"code":32,"message":"Could…'; error='?',
bentolor/Twitter, timeline:home, userId:1, ;
Load Timeline,
Status code=UNAUTHORIZED; hard;
statusLine:'HTTP/1.1 401 Authorization Required'; statusLine:'HTTP/1.1 401 Authorization Required'; statusCode:UNAUTHORIZED (401); url:'https://api.twitter.com/1.1/statuses/mentions_timeline.json?since_id=701039673519579136&count=200&user_id=2222222222'; authenticated; response:'{"errors":[{"code":32,"message":"Could…'; error='?',
bentolor/Twitter, timeline:mentions, userId:1, ;
Load Timeline,
Status code=UNAUTHORIZED; hard;
statusLine:'HTTP/1.1 401 Authorization Required'; statusLine:'HTTP/1.1 401 Authorization Required'; statusCode:UNAUTHORIZED (401); url:'https://api.twitter.com/1.1/direct_messages.json?since_id=696740068975906823&count=200&user_id=2222222222'; authenticated; response:'{"errors":[{"code":32,"message":"Could…'; error='?',
bentolor/Twitter, timeline:direct, userId:1}}
2016-04-14-08-54-06 D/MyService: saveQueue-to-ERROR; 3 saved
2016-04-14-08-54-06 D/MyService: State saved, no  msg in the Queues, 3 in Error queue
2016-04-14-08-54-06 D/MyService: Releasing wakelock
2016-04-14-08-54-06 V/HeartBeat: Ended; HeartBeat 0; org.andstatus.app.service.MyService$HeartBeat on SYNC; age 2sec; RUNNING 2sec, cancelled; instanceId=114; org.andstatus.app.service.MyService$HeartBeat@6d19fe6c - InterruptedException
```

**Comment by yvolk** [comment] 2016-04-14 16:37
This is expected behaviour for Twitter.
You had to Reverify/reauthorize your Twitter account. AndStatus, distributed via Google Play, and via F-Droid are different applications from Twitter's point of view.

**Comment by yvolk** [comment] 2016-04-14 16:40
@alanz  I figured out, that I determined cache size incorrectly. Will fix this today and let you know!

**Comment by alanz** [comment] 2016-04-14 18:09
Thanks.

BTW, after deleting all app data and reverifying credentials it started
working again, once it had downloaded everything

**Comment by yvolk** [comment] 2016-04-15 16:27
@alanz v.25.04 in Beta now. Please send me crash report if you have a chance...

**Comment by alanz** [comment] 2016-04-16 11:13
Have run it for a while, seems to be behaving perfectly.

On interesting thing is, when loading I timeline from scratch, and I guess while it is still loading the rest of it, the images are spaced in the middle of the post, with quite a lot of blank space above and below (about 25% of the screen for each).  After a while it settles down and then works fine on that timeline from then on.

**Comment by yvolk** [comment] 2016-04-16 12:55
@alanz I described above why this happens. I will improve this soon...

**Comment by yvolk** [comment] 2016-04-17 05:19
As I created #360 for blank spaces, I'm closing this issue.

**Closed by yvolk** 2016-04-17 05:19 UTC
Labels: UX enhancement
