### ISSUE TITLE
Wrong password show the error

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#198] opened 2014-12-21 14:41 UTC
I don't know if it's because the debugging option, but now, AS doesn't show a merge message like "Wrong password" or something. It's just a report, I don't know if it's apropos.

**Comment by yvolk** [comment] 2015-01-11 14:19
Closing this ticket as not a bug.
Leaving a User without any explanation about the cause of the authentication failure is not good, I think.
Of cause I agree that the error message itself may be improved, localized etc... But this is another story :-)
So far after extending error reporting in AndStatus I got positive and valuable feedback (which is helping in fixing real issues both in AndStatus and in Social platforms...)

**Closed by yvolk** 2015-01-11 14:19 UTC
