### ISSUE TITLE
Old notes first in a Timeline

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#509] opened 2019-05-25 19:42 UTC
For more than two years AndStatus has "Old notes first in a Conversation view" option. But Timelines don't have similar option.

As @BalooUriza notes, suggesting this feature: "Trying to read backwards is mindbending" :-)

**Comment by polyzen** [comment] 2019-10-19 10:06
Duplicate of #377

**Closed** 2019-10-19 10:43 UTC
Labels: Duplicate, UX enhancement
